apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
  namespace: dev # <--- Namespace Dev
data:
  config.js: |
    window.ENV = {
      TODO_API_URL: "http://192.168.40.121:32080/todos",
      USER_API_URL: "http://192.168.40.121:32081/users",
      STATS_API_URL: "http://192.168.40.121:32082/stats"
    };
