apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
  namespace: prod
data:
  config.js: |
    window.ENV = {
      // Chỉ cần trỏ vào path, trình duyệt sẽ tự hiểu là cùng domain hiện tại
      TODO_API_URL: "/todos",
      USER_API_URL: "/users",
      STATS_API_URL: "/stats"
    };
