apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
  namespace: prod
data:
  config.js: |
    window.ENV = {
      TODO_API_URL: "http://192.168.40.200:8080/todos",
      USER_API_URL: "http://192.168.40.201:8081/users",
      STATS_API_URL: "http://192.168.40.202:8082/stats"
    };
