prometheus:
  prometheusSpec:
    nodeSelector:
      role: monitoring
    retention: 10d

alertmanager:
  alertmanagerSpec:
    nodeSelector:
      role: monitoring

grafana:
  nodeSelector:
    role: monitoring
  service:
    type: NodePort
    nodePort: 31000  # Mở cổng 31000 ra ngoài
  defaultTimezone: Asia/Ho_Chi_Minh

prometheusOperator:
  nodeSelector:
    role: monitoring

# Tắt các thành phần không cần thiết
kubeEtcd:
  enabled: false
kubeControllerManager:
  enabled: false
kubeScheduler:
  enabled: false
